export const DBVersionSchema = {
	title: "number schema",
	version: 0,
	primaryKey: "id",
	type: "object",
	properties: {
		id: {
			type: "string",
			// primary: true,
			maxLength: 100,
		},
		value: {
			type: "number",
		},
	},
	required: ["id", "value"],
};

export default {
	title: "transfers schema",
	version: 0,
	description: "Describes a single transfer",
	primaryKey: "id",
	type: "object",
	properties: {
		id: { type: "number", primary: true, maxLength: 100 },
		pid: { type: "string" },
		n: { type: "string" },
		c: { type: "string" },
		a: { type: "number" },
		h: { type: "number" },
		w: { type: "number" },
		s: { type: "string" },
		wk: { type: "number" },
		p: { type: "number" },
		f: { type: "number" },
		st: { type: "number" },
		pc: { type: "number" },
		tc: { type: "number" },
		ps: { type: "number" },
		kp: { type: "number" },
		df: { type: "number" },
		pm: { type: "number" },
		sr: { type: "number" },
		si: { type: "string" },
		bi: { type: "string" },
		ss: { type: "number" },
		ass: { type: "number" },
		dss: { type: "number" },
		mss: { type: "number" },
		gss: { type: "number" },
		tt: { type: "number" },
	},
	required: [
		"id",
		"pid",
		"n",
		"c",
		"a",
		"h",
		"w",
		"s",
		"wk",
		"p",
		"f",
		"st",
		"pc",
		"tc",
		"ps",
		"kp",
		"df",
		"pm",
		"sr",
		"si",
		"bi",
		"ss",
		"ass",
		"dss",
		"mss",
		"gss",
		"tt",
	],
	indexes: [
		"tt", // For your primary sort
		["tt", "ss"], // For common combinations
		["tt", "p"],
		["tt", "a"],
		["tt", "c"],
		// Only add these if you frequently filter on these exact combinations
		["tt", "ss", "p"],
		["tt", "a", "c"],
	],
};
