export default [
	{ country: "Polska", currency: "zł", rate: 1 },
	{ country: "New Zealand", currency: "NZ$", rate: 0.4 },
	{ country: "England", currency: "£", rate: 1.666668 },
	{ country: "USA", currency: "$", rate: 1 },
	{ country: "Canada", currency: "C$", rate: 0.625 },
	{ country: "Australia", currency: "AU$", rate: 0.625 },
	{ country: "Scotland", currency: "£", rate: 1.666668 },
	{ country: "Magyarország", currency: "Ft", rate: 0.005 },
	{ country: "România", currency: "lei", rate: 0.25 },
	{ country: "Italia", currency: "€", rate: 1 },
	{ country: "Jamaica", currency: "J$", rate: 0.01 },
	{ country: "Nederland", currency: "€", rate: 1 },
	{ country: "Česká republika", currency: "Kč", rate: 0.033334 },
	{ country: "Slovensko", currency: "€", rate: 1 },
	{ country: "Deutschland", currency: "€", rate: 1 },
	{ country: "France", currency: "€", rate: 1 },
	{ country: "España", currency: "€", rate: 1 },
	{ country: "México", currency: "$ MN", rate: 0.083334 },
	{ country: "Argentina", currency: "u$s", rate: 1 },
	{ country: "Portugal", currency: "€", rate: 1 },
	{ country: "Brasil", currency: "R$", rate: 0.25 },
	{ country: "South Africa", currency: "R", rate: 0.125 },
	{ country: "Lietuva", currency: "€", rate: 1 },
	{ country: "Schweiz", currency: "CHF", rate: 0.625 },
	{ country: "Suomi", currency: "€", rate: 1 },
	{ country: "Slovenija", currency: "€", rate: 1 },
	{ country: "Norge", currency: "kr.", rate: 0.125 },
	{ country: "België", currency: "€", rate: 1 },
	{ country: "Danmark", currency: "kr.", rate: 0.125 },
	{ country: "Österreich", currency: "€", rate: 1 },
	{ country: "Sverige", currency: "kr", rate: 0.125 },
	{ country: "Ireland", currency: "€", rate: 1 },
	{ country: "Eesti", currency: "€", rate: 1 },
	{ country: "Hrvatska", currency: "€", rate: 1 },
	{ country: "Uruguay", currency: "$U", rate: 0.03125 },
	{ country: "Colombia", currency: "k.$", rate: 0.3125 },
	{ country: "Perú", currency: "sol", rate: 0.25 },
	{ country: "Nigeria", currency: "₦", rate: 0.555555 },
	{ country: "Srbija", currency: "din", rate: 0.0125 },
	{ country: "Cymru", currency: "£", rate: 1.666668 },
	{ country: "Türkiye", currency: "TL", rate: 0.625 },
	{ country: "Chile", currency: "k.$", rate: 1.25 },
	{ country: "Rossiya", currency: "руб.", rate: 0.03125 },
	{ country: "Venezuela", currency: "k Bs.", rate: 0.3125 },
	{ country: "Latvija", currency: "€", rate: 1 },
	{ country: "Belarus", currency: "к руб.", rate: 0.3125 },
	{ country: "Bosna i Hercegovina", currency: "KM", rate: 0.5 },
	{ country: "Misr", currency: "E£", rate: 0.125 },
	{ country: "Hellas", currency: "€", rate: 1 },
	{ country: "Ghana", currency: "k.¢", rate: 0.08 },
	{ country: "India", currency: "Rs.", rate: 0.02 },
	{ country: "Israel", currency: "₪", rate: 0.166667 },
	{ country: "Shqipëria", currency: "lek", rate: 0.01 },
	{ country: "Bulgaria", currency: "лв.", rate: 0.5 },
	{ country: "Lëtzebuerg", currency: "€", rate: 1 },
	{ country: "Severna Makedonija", currency: "ден.", rate: 0.0125 },
	{ country: "Bolivia", currency: "Bs", rate: 0.1 },
	{ country: "Ecuador", currency: "U$S", rate: 1 },
	{ country: "Malaysia", currency: "RM", rate: 0.2 },
	{ country: "Hong Kong", currency: "HK$", rate: 0.1 },
	{ country: "República Dominicana", currency: "RD$", rate: 0.025 },
	{ country: "Nippon", currency: "¥", rate: 0.00625 },
	{ country: "Ísland", currency: "kr", rate: 0.0125 },
	{ country: "Ukraina", currency: "грн.", rate: 0.15625 },
	{ country: "Indonesia", currency: "k Rp", rate: 0.1 },
	{ country: "Hayastan", currency: "Դրամ", rate: 2 },
	{ country: "Malta", currency: "€", rate: 1 },
	{ country: "Honduras", currency: "L", rate: 0.05 },
	{ country: "Moldova", currency: "lei", rate: 0.0625 },
	{ country: "Costa Rica", currency: "k ¢", rate: 1.5625 },
	{ country: "Andorra", currency: "€", rate: 1 },
	{ country: "Paraguay", currency: "k G", rate: 0.125 },
	{ country: "Panamá", currency: "$", rate: 1 },
	{ country: "Crna Gora", currency: "€", rate: 1 },
	{ country: "Kenya", currency: "Sh", rate: 0.01 },
	{ country: "Guatemala", currency: "Q", rate: 0.1 },
	{ country: "Daehan Minguk", currency: "k. ₩", rate: 0.8 },
	{ country: "Azərbaycan", currency: "m", rate: 0.8 },
	{ country: "Cameroun", currency: "k. Fr", rate: 1.5625 },
	{ country: "Sénégal", currency: "k. Fr", rate: 1.5625 },
	{ country: "Zhōngguó", currency: "¥", rate: 0.1 },
	{ country: "Singapore", currency: "S$", rate: 0.5 },
	{ country: "Việt Nam", currency: "k.₫", rate: 0.05 },
	{ country: "Kypros", currency: "€", rate: 1 },
	{ country: "Īrān", currency: "k.‏ريال‎", rate: 0.0625 },
	{ country: "Tūnis", currency: "‏د‎.‏ت‎", rate: 0.5 },
	{ country: "as-Saʻūdiyya", currency: "‏ريال‎", rate: 0.195313 },
	{ country: "Al Maghrib", currency: "‏درهم‎", rate: 0.08 },
	{ country: "Prathet Thai", currency: "฿", rate: 0.02 },
	{ country: "El Salvador", currency: "$", rate: 1 },
	{ country: "Pilipinas", currency: "P", rate: 0.15625 },
	{ country: "Cuba", currency: "$MN", rate: 0.625 },
	{ country: "U.A.E.", currency: "‏د‎.‏إ‎", rate: 0.15625 },
	{ country: "Nicaragua", currency: "C$", rate: 0.05 },
	{ country: "Kazakhstán", currency: "T", rate: 0.00625 },
	{ country: "O‘zbekiston", currency: "k so‘m", rate: 0.625 },
	{ country: "al-Jazā’ir", currency: "‏دج‎", rate: 0.0125 },
	{ country: "Sakartvelo", currency: "ლ", rate: 0.5 },
];
