// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Transfer } from '../transfers/transfer.js';


export class TransferList {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TransferList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTransferList(bb:flatbuffers.ByteBuffer, obj?:TransferList):TransferList {
  return (obj || new TransferList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTransferList(bb:flatbuffers.ByteBuffer, obj?:TransferList):TransferList {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TransferList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

transfers(index: number, obj?:Transfer):Transfer|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Transfer()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

transfersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startTransferList(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addTransfers(builder:flatbuffers.Builder, transfersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, transfersOffset, 0);
}

static createTransfersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTransfersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endTransferList(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishTransferListBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedTransferListBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createTransferList(builder:flatbuffers.Builder, transfersOffset:flatbuffers.Offset):flatbuffers.Offset {
  TransferList.startTransferList(builder);
  TransferList.addTransfers(builder, transfersOffset);
  return TransferList.endTransferList(builder);
}
}
