// Currency and locale mapping for countries
export const currencyMapping = {
	ma: { currency: "MAD", locale: "ar-MA" },
	dz: { currency: "DZD", locale: "ar-DZ" },
	ad: { currency: "EUR", locale: "ca-AD" },
	ar: { currency: "ARS", locale: "es-AR" },
	sa: { currency: "SAR", locale: "ar-SA" },
	au: { currency: "AUD", locale: "en-AU" },
	az: { currency: "AZN", locale: "az-AZ" },
	by: { currency: "BYN", locale: "be-BY" },
	be: { currency: "EUR", locale: "nl-BE" },
	bo: { currency: "BOB", locale: "es-BO" },
	ba: { currency: "BAM", locale: "bs-BA" },
	br: { currency: "BRL", locale: "pt-BR" },
	bg: { currency: "BGN", locale: "bg-BG" },
	cm: { currency: "XAF", locale: "fr-CM" },
	ca: { currency: "CAD", locale: "en-CA" },
	cz: { currency: "CZK", locale: "cs-CZ" },
	cl: { currency: "CLP", locale: "es-CL" },
	co: { currency: "COP", locale: "es-CO" },
	cr: { currency: "CRC", locale: "es-CR" },
	me: { currency: "EUR", locale: "sr-ME" },
	cu: { currency: "CUP", locale: "es-CU" },
	gb: { currency: "GBP", locale: "en-GB" },
	kr: { currency: "KRW", locale: "ko-KR" },
	dk: { currency: "DKK", locale: "da-DK" },
	de: { currency: "EUR", locale: "de-DE" },
	ec: { currency: "USD", locale: "es-EC" },
	ee: { currency: "EUR", locale: "et-EE" },
	sv: { currency: "USD", locale: "es-SV" },
	en: { currency: "GBP", locale: "en-GB" },
	es: { currency: "EUR", locale: "es-ES" },
	fr: { currency: "EUR", locale: "fr-FR" },
	gh: { currency: "GHS", locale: "en-GH" },
	gt: { currency: "GTQ", locale: "es-GT" },
	am: { currency: "AMD", locale: "hy-AM" },
	el: { currency: "EUR", locale: "el-GR" },
	hn: { currency: "HNL", locale: "es-HN" },
	hk: { currency: "HKD", locale: "zh-HK" },
	hr: { currency: "EUR", locale: "hr-HR" },
	in: { currency: "INR", locale: "hi-IN" },
	id: { currency: "IDR", locale: "id-ID" },
	ir: { currency: "IRR", locale: "fa-IR" },
	ie: { currency: "EUR", locale: "en-IE" },
	is: { currency: "ISK", locale: "is-IS" },
	il: { currency: "ILS", locale: "he-IL" },
	it: { currency: "EUR", locale: "it-IT" },
	jm: { currency: "JMD", locale: "en-JM" },
	kz: { currency: "KZT", locale: "kk-KZ" },
	ke: { currency: "KES", locale: "sw-KE" },
	cy: { currency: "EUR", locale: "el-CY" },
	lv: { currency: "EUR", locale: "lv-LV" },
	lu: { currency: "EUR", locale: "lb-LU" },
	lt: { currency: "EUR", locale: "lt-LT" },
	hu: { currency: "HUF", locale: "hu-HU" },
	my: { currency: "MYR", locale: "ms-MY" },
	mt: { currency: "EUR", locale: "mt-MT" },
	mx: { currency: "MXN", locale: "es-MX" },
	eg: { currency: "EGP", locale: "ar-EG" },
	md: { currency: "MDL", locale: "ro-MD" },
	nl: { currency: "EUR", locale: "nl-NL" },
	nz: { currency: "NZD", locale: "en-NZ" },
	ni: { currency: "NIO", locale: "es-NI" },
	ng: { currency: "NGN", locale: "en-NG" },
	jp: { currency: "JPY", locale: "ja-JP" },
	no: { currency: "NOK", locale: "nb-NO" },
	at: { currency: "EUR", locale: "de-AT" },
	uz: { currency: "UZS", locale: "uz-UZ" },
	pa: { currency: "PAB", locale: "es-PA" },
	py: { currency: "PYG", locale: "es-PY" },
	pe: { currency: "PEN", locale: "es-PE" },
	ph: { currency: "PHP", locale: "fil-PH" },
	pl: { currency: "PLN", locale: "pl-PL" },
	pt: { currency: "EUR", locale: "pt-PT" },
	th: { currency: "THB", locale: "th-TH" },
	do: { currency: "DOP", locale: "es-DO" },
	ro: { currency: "RON", locale: "ro-RO" },
	ru: { currency: "RUB", locale: "ru-RU" },
	ge: { currency: "GEL", locale: "ka-GE" },
	ch: { currency: "CHF", locale: "de-CH" },
	sn: { currency: "XOF", locale: "fr-SN" },
	mk: { currency: "MKD", locale: "mk-MK" },
	al: { currency: "ALL", locale: "sq-AL" },
	sg: { currency: "SGD", locale: "en-SG" },
	si: { currency: "EUR", locale: "sl-SI" },
	sk: { currency: "EUR", locale: "sk-SK" },
	za: { currency: "ZAR", locale: "en-ZA" },
	rs: { currency: "RSD", locale: "sr-RS" },
	fi: { currency: "EUR", locale: "fi-FI" },
	se: { currency: "SEK", locale: "sv-SE" },
	tn: { currency: "TND", locale: "ar-TN" },
	tr: { currency: "TRY", locale: "tr-TR" },
	ae: { currency: "AED", locale: "ar-AE" },
	uk: { currency: "UAH", locale: "uk-UA" },
	uy: { currency: "UYU", locale: "es-UY" },
	us: { currency: "USD", locale: "en-US" },
	ve: { currency: "VES", locale: "es-VE" },
	vn: { currency: "VND", locale: "vi-VN" },
	zh: { currency: "CNY", locale: "zh-CN" },
};

const countries = [
	{
		code: 89,
		name: "Al Maghrib",
		icon: "🇲🇦",
		rate: 0.08,
		countryCode: "ma",
	},
	{
		code: 105,
		name: "al-Jazā'ir",
		icon: "🇩🇿",
		rate: 0.0125,
		countryCode: "dz",
	},
	{
		code: 71,
		name: "Andorra",
		icon: "🇦🇩",
		rate: 1.0,
		countryCode: "ad",
	},
	{
		code: 19,
		name: "Argentina",
		icon: "🇦🇷",
		rate: 1.0,
		countryCode: "ar",
	},
	{
		code: 88,
		name: "as-Saʻūdiyya",
		icon: "🇸🇦",
		rate: 0.195313,
		countryCode: "sa",
	},
	{
		code: 6,
		name: "Australia",
		icon: "🇦🇺",
		rate: 0.625,
		countryCode: "au",
	},
	{
		code: 79,
		name: "Azərbaycan",
		icon: "🇦🇿",
		rate: 0.8,
		countryCode: "az",
	},
	{
		code: 46,
		name: "Belarus",
		icon: "🇧🇾",
		rate: 0.3125,
		countryCode: "by",
	},
	{
		code: 28,
		name: "België",
		icon: "🇧🇪",
		rate: 1.0,
		countryCode: "be",
	},
	{
		code: 57,
		name: "Bolivia",
		icon: "🇧🇴",
		rate: 0.1,
		countryCode: "bo",
	},
	{
		code: 47,
		name: "Bosna i Hercegovina",
		icon: "🇧🇦",
		rate: 0.5,
		countryCode: "ba",
	},
	{
		code: 21,
		name: "Brasil",
		icon: "🇧🇷",
		rate: 0.25,
		countryCode: "br",
	},
	{
		code: 54,
		name: "Bulgaria",
		icon: "🇧🇬",
		rate: 0.5,
		countryCode: "bg",
	},
	{
		code: 80,
		name: "Cameroun",
		icon: "🇨🇲",
		rate: 1.5625,
		countryCode: "cm",
	},
	{
		code: 5,
		name: "Canada",
		icon: "🇨🇦",
		rate: 0.625,
		countryCode: "ca",
	},
	{
		code: 13,
		name: "Česká republika",
		icon: "🇨🇿",
		rate: 0.033334,
		countryCode: "cz",
	},
	{
		code: 42,
		name: "Chile",
		icon: "🇨🇱",
		rate: 1.25,
		countryCode: "cl",
	},
	{
		code: 36,
		name: "Colombia",
		icon: "🇨🇴",
		rate: 0.3125,
		countryCode: "co",
	},
	{
		code: 70,
		name: "Costa Rica",
		icon: "🇨🇷",
		rate: 1.5625,
		countryCode: "cr",
	},
	{
		code: 75,
		name: "Crna Gora",
		icon: "🇲🇪",
		rate: 1.0,
		countryCode: "me",
	},
	{
		code: 97,
		name: "Cuba",
		icon: "🇨🇺",
		rate: 0.625,
		countryCode: "cu",
	},
	{
		code: 40,
		name: "Cymru",
		icon: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
		rate: 1.666668,
		countryCode: "gb",
	},
	{
		code: 78,
		name: "Daehan Minguk",
		icon: "🇰🇷",
		rate: 0.8,
		countryCode: "kr",
	},
	{
		code: 29,
		name: "Danmark",
		icon: "🇩🇰",
		rate: 0.125,
		countryCode: "dk",
	},
	{
		code: 15,
		name: "Deutschland",
		icon: "🇩🇪",
		rate: 1.0,
		countryCode: "de",
	},
	{
		code: 58,
		name: "Ecuador",
		icon: "🇪🇨",
		rate: 1.0,
		countryCode: "ec",
	},
	{
		code: 33,
		name: "Eesti",
		icon: "🇪🇪",
		rate: 1.0,
		countryCode: "ee",
	},
	{
		code: 92,
		name: "El Salvador",
		icon: "🇸🇻",
		rate: 1.0,
		countryCode: "sv",
	},
	{
		code: 3,
		name: "England",
		icon: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
		rate: 1.666668,
		countryCode: "en",
	},
	{
		code: 17,
		name: "España",
		icon: "🇪🇸",
		rate: 1.0,
		countryCode: "es",
	},
	{
		code: 16,
		name: "France",
		icon: "🇫🇷",
		rate: 1.0,
		countryCode: "fr",
	},
	{
		code: 50,
		name: "Ghana",
		icon: "🇬🇭",
		rate: 0.08,
		countryCode: "gh",
	},
	{
		code: 77,
		name: "Guatemala",
		icon: "🇬🇹",
		rate: 0.1,
		countryCode: "gt",
	},
	{
		code: 66,
		name: "Hayastan",
		icon: "🇦🇲",
		rate: 2.0,
		countryCode: "am",
	},
	{
		code: 49,
		name: "Hellas",
		icon: "🇬🇷",
		rate: 1.0,
		countryCode: "el",
	},
	{
		code: 68,
		name: "Honduras",
		icon: "🇭🇳",
		rate: 0.05,
		countryCode: "hn",
	},
	{
		code: 60,
		name: "Hong Kong",
		icon: "🇭🇰",
		rate: 0.1,
		countryCode: "hk",
	},
	{
		code: 34,
		name: "Hrvatska",
		icon: "🇭🇷",
		rate: 1.0,
		countryCode: "hr",
	},
	{
		code: 51,
		name: "India",
		icon: "🇮🇳",
		rate: 0.02,
		countryCode: "in",
	},
	{
		code: 65,
		name: "Indonesia",
		icon: "🇮🇩",
		rate: 0.1,
		countryCode: "id",
	},
	{
		code: 86,
		name: "Īrān",
		icon: "🇮🇷",
		rate: 0.0625,
		countryCode: "ir",
	},
	{
		code: 32,
		name: "Ireland",
		icon: "🇮🇪",
		rate: 1.0,
		countryCode: "ie",
	},
	{
		code: 63,
		name: "Ísland",
		icon: "🇮🇸",
		rate: 0.0125,
		countryCode: "is",
	},
	{
		code: 52,
		name: "Israel",
		icon: "🇮🇱",
		rate: 0.166667,
		countryCode: "il",
	},
	{
		code: 10,
		name: "Italia",
		icon: "🇮🇹",
		rate: 1.0,
		countryCode: "it",
	},
	{
		code: 11,
		name: "Jamaica",
		icon: "🇯🇲",
		rate: 0.01,
		countryCode: "jm",
	},
	{
		code: 103,
		name: "Kazakhstán",
		icon: "🇰🇿",
		rate: 0.00625,
		countryCode: "kz",
	},
	{
		code: 76,
		name: "Kenya",
		icon: "🇰🇪",
		rate: 0.01,
		countryCode: "ke",
	},
	{
		code: 85,
		name: "Kypros",
		icon: "🇨🇾",
		rate: 1.0,
		countryCode: "cy",
	},
	{
		code: 45,
		name: "Latvija",
		icon: "🇱🇻",
		rate: 1.0,
		countryCode: "lv",
	},
	{
		code: 55,
		name: "Lëtzebuerg",
		icon: "🇱🇺",
		rate: 1.0,
		countryCode: "lu",
	},
	{
		code: 23,
		name: "Lietuva",
		icon: "🇱🇹",
		rate: 1.0,
		countryCode: "lt",
	},
	{
		code: 8,
		name: "Magyarország",
		icon: "🇭🇺",
		rate: 0.005,
		countryCode: "hu",
	},
	{
		code: 59,
		name: "Malaysia",
		icon: "🇲🇾",
		rate: 0.2,
		countryCode: "my",
	},
	{
		code: 67,
		name: "Malta",
		icon: "🇲🇹",
		rate: 1.0,
		countryCode: "mt",
	},
	{
		code: 18,
		name: "México",
		icon: "🇲🇽",
		rate: 0.083334,
		countryCode: "mx",
	},
	{
		code: 48,
		name: "Misr",
		icon: "🇪🇬",
		rate: 0.125,
		countryCode: "eg",
	},
	{
		code: 69,
		name: "Moldova",
		icon: "🇲🇩",
		rate: 0.0625,
		countryCode: "md",
	},
	{
		code: 12,
		name: "Nederland",
		icon: "🇳🇱",
		rate: 1.0,
		countryCode: "nl",
	},
	{
		code: 2,
		name: "New Zealand",
		icon: "🇳🇿",
		rate: 0.625,
		countryCode: "nz",
	},
	{
		code: 100,
		name: "Nicaragua",
		icon: "🇳🇮",
		rate: 0.05,
		countryCode: "ni",
	},
	{
		code: 38,
		name: "Nigeria",
		icon: "🇳🇬",
		rate: 0.555555,
		countryCode: "ng",
	},
	{
		code: 62,
		name: "Nippon",
		icon: "🇯🇵",
		rate: 0.00625,
		countryCode: "jp",
	},
	{
		code: 27,
		name: "Norge",
		icon: "🇳🇴",
		rate: 0.125,
		countryCode: "no",
	},
	{
		code: 30,
		name: "Österreich",
		icon: "🇦🇹",
		rate: 1.0,
		countryCode: "at",
	},
	{
		code: 104,
		name: "O'zbekiston",
		icon: "🇺🇿",
		rate: 0.625,
		countryCode: "uz",
	},
	{
		code: 73,
		name: "Panamá",
		icon: "🇵🇦",
		rate: 1.0,
		countryCode: "pa",
	},
	{
		code: 72,
		name: "Paraguay",
		icon: "🇵🇾",
		rate: 0.125,
		countryCode: "py",
	},
	{
		code: 37,
		name: "Perú",
		icon: "🇵🇪",
		rate: 0.25,
		countryCode: "pe",
	},
	{
		code: 96,
		name: "Pilipinas",
		icon: "🇵🇭",
		rate: 0.15625,
		countryCode: "ph",
	},
	{
		code: 1,
		name: "Polska",
		icon: "🇵🇱",
		rate: 0.25,
		countryCode: "pl",
	},
	{
		code: 20,
		name: "Portugal",
		icon: "🇵🇹",
		rate: 1.0,
		countryCode: "pt",
	},
	{
		code: 90,
		name: "Prathet Thai",
		icon: "🇹🇭",
		rate: 0.02,
		countryCode: "th",
	},
	{
		code: 61,
		name: "República Dominicana",
		icon: "🇩🇴",
		rate: 0.025,
		countryCode: "do",
	},
	{
		code: 9,
		name: "România",
		icon: "🇷🇴",
		rate: 0.25,
		countryCode: "ro",
	},
	{
		code: 43,
		name: "Rossiya",
		icon: "🇷🇺",
		rate: 0.03125,
		countryCode: "ru",
	},
	{
		code: 106,
		name: "Sakartvelo",
		icon: "🇬🇪",
		rate: 0.5,
		countryCode: "ge",
	},
	{
		code: 24,
		name: "Schweiz",
		icon: "🇨🇭",
		rate: 0.625,
		countryCode: "ch",
	},
	{
		code: 7,
		name: "Scotland",
		icon: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
		rate: 1.666668,
		countryCode: "gb",
	},
	{
		code: 81,
		name: "Sénégal",
		icon: "🇸🇳",
		rate: 1.5625,
		countryCode: "sn",
	},
	{
		code: 56,
		name: "Severna Makedonija",
		icon: "🇲🇰",
		rate: 0.0125,
		countryCode: "mk",
	},
	{
		code: 53,
		name: "Shqipëria",
		icon: "🇦🇱",
		rate: 0.01,
		countryCode: "al",
	},
	{
		code: 83,
		name: "Singapore",
		icon: "🇸🇬",
		rate: 0.5,
		countryCode: "sg",
	},
	{
		code: 26,
		name: "Slovenija",
		icon: "🇸🇮",
		rate: 1.0,
		countryCode: "si",
	},
	{
		code: 14,
		name: "Slovensko",
		icon: "🇸🇰",
		rate: 1.0,
		countryCode: "sk",
	},
	{
		code: 22,
		name: "South Africa",
		icon: "🇿🇦",
		rate: 0.125,
		countryCode: "za",
	},
	{
		code: 39,
		name: "Srbija",
		icon: "🇷🇸",
		rate: 0.0125,
		countryCode: "rs",
	},
	{
		code: 25,
		name: "Suomi",
		icon: "🇫🇮",
		rate: 1.0,
		countryCode: "fi",
	},
	{
		code: 31,
		name: "Sverige",
		icon: "🇸🇪",
		rate: 0.125,
		countryCode: "se",
	},
	{
		code: 87,
		name: "Tūnis",
		icon: "🇹🇳",
		rate: 0.5,
		countryCode: "tn",
	},
	{
		code: 41,
		name: "Türkiye",
		icon: "🇹🇷",
		rate: 0.625,
		countryCode: "tr",
	},
	{
		code: 99,
		name: "U.A.E.",
		icon: "🇦🇪",
		rate: 0.15625,
		countryCode: "ae",
	},
	{
		code: 64,
		name: "Ukraina",
		icon: "🇺🇦",
		rate: 0.15625,
		countryCode: "uk",
	},
	{
		code: 35,
		name: "Uruguay",
		icon: "🇺🇾",
		rate: 0.03125,
		countryCode: "uy",
	},
	{
		code: 4,
		name: "USA",
		icon: "🇺🇸",
		rate: 1.0,
		countryCode: "us",
	},
	{
		code: 44,
		name: "Venezuela",
		icon: "🇻🇪",
		rate: 0.3125,
		countryCode: "ve",
	},
	{
		code: 84,
		name: "Việt Nam",
		icon: "🇻🇳",
		rate: 0.05,
		countryCode: "vn",
	},
	{
		code: 82,
		name: "Zhōngguó",
		icon: "🇨🇳",
		rate: 0.1,
		countryCode: "zh",
	},
] as const;

export default countries;
